#!/usr/bin/env python3
"""
build_assets.py
Embeds index.html, styles.css, and app.js into dashboard_assets.h as gzipped PROGMEM byte arrays.
Uses Python stdlib only (gzip, os, sys).
"""
import gzip
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_HEADER = os.path.join(SCRIPT_DIR, "dashboard_assets.h")

ASSETS = [
    ("INDEX_HTML_GZ", "index.html"),
    ("STYLES_CSS_GZ", "styles.css"),
    ("APP_JS_GZ", "app.js"),
]

def file_to_c_array(name, data):
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    hex_bytes = [f"0x{b:02x}" for b in data]
    for i in range(0, len(hex_bytes), 16):
        lines.append("  " + ", ".join(hex_bytes[i:i + 16]) + ",")
    lines.append("};")
    lines.append(f"const size_t {name}_LEN = {len(data)};\n")
    return "\n".join(lines)

def main():
    out = []
    out.append("// Auto-generated by build_assets.py. Do not edit directly.")
    out.append("#ifndef DASHBOARD_ASSETS_H")
    out.append("#define DASHBOARD_ASSETS_H\n")
    out.append("#include <Arduino.h>\n")

    total_orig = 0
    total_gz = 0

    for var_name, file_name in ASSETS:
        file_path = os.path.join(SCRIPT_DIR, file_name)
        if not os.path.exists(file_path):
            sys.stderr.write(f"Error: {file_path} not found\n")
            sys.exit(1)
        with open(file_path, "rb") as f:
            raw = f.read()
        gz = gzip.compress(raw, compresslevel=9)
        total_orig += len(raw)
        total_gz += len(gz)
        print(f"Compressed {file_name}: {len(raw)} -> {len(gz)} bytes ({len(gz)*100/len(raw):.1f}%)")
        out.append(file_to_c_array(var_name, gz))

    out.append("#endif // DASHBOARD_ASSETS_H\n")

    with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    print(f"Generated {OUTPUT_HEADER} (Total gz: {total_gz} bytes, saved {total_orig - total_gz} bytes)")

if __name__ == "__main__":
    main()
